additionalArguments:
  - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
  - --certificatesresolvers.letsencrypt.acme.email=youremail@domain.com
  - --certificatesresolvers.letsencrypt.acme.storage=/data/letsencrypt.json
  